---
- hosts: cluster
  roles:
    - role: build_hosts
    
- hosts: elastic01
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "3g"
    es_config:
      cluster.name: "luisfilho"
      cluster.initial_master_nodes: "elastic01,elastic02,elastic03"
      discovery.seed_hosts: "elastic01,elastic02,elastic03"
      http.port: 9200
      bootstrap.memory_lock: false
      network.host: _site_
    es_api_host: "10.150.0.20"

- hosts: elastic02
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "3g"
    es_config:
      cluster.name: "luisfilho"
      cluster.initial_master_nodes: "elastic01,elastic02,elastic03"
      discovery.seed_hosts: "elastic01,elastic02,elastic03"
      http.port: 9200
      bootstrap.memory_lock: false
      network.host: _site_
    es_api_host: "10.150.0.21"

- hosts: elastic03
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "3g"
    es_config:
      cluster.name: "luisfilho"
      cluster.initial_master_nodes: "elastic01,elastic02,elastic03"
      discovery.seed_hosts: "elastic01,elastic02,elastic03"
      http.port: 9200
      bootstrap.memory_lock: false
      network.host: _site_
    es_api_host: "10.150.0.22"

- hosts: elastic-01
  roles:
    - role: geerlingguy.kibana
  vars:
    - kibana_elasticsearch_url: "['http://elastic01:9200', 'http://elastic02:9200', 'http://elastic03:9200']"
    - kibana_version: "7.x"

- hosts: elastic02
  roles:
    - role: geerlingguy.logstash
  vars:
    - logstash_version: "7.x"
