- hosts: elastictcc-01
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "3g"
    es_config:
      cluster.name: "luis.filho"
      cluster.initial_master_nodes: "elastictcc-01,elastictcc-02,elastictcc-03"
      discovery.seed_hosts: "elastictcc-01,elastictcc-02,elastictcc-03"
      http.port: 9200
      bootstrap.memory_lock: false
      network.host: _site_
    es_api_host: "10.150.0.20"
